server:
  port: 80
spring:
  application.name: iebook
  datasource:
     url: jdbc:mysql://45.76.203.73:3306/iebook?useUnicode=true&characterEncoding=utf-8
     username: root
     password:
     driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
     mode: HTML
     cache: false
     prefix: classpath:/templates

# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
web:
  basepath: /iebook/files
  bookpath: ${web.basepath}bookpath/
  photo: ${web.basepath}photo/