server:
  port: 80
spring:
  application.name: iebook
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/iebook?useUnicode=true&characterEncoding=utf-8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
     mode: HTML
     cache: false
# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql